spring.application.name=Demo

# DATA BASE CONFIGURATION
spring.datasource.url=jdbc:h2:mem:demo;
spring.datasource.username=user
spring.datasource.password=user123

#user name and password for login



app.jwt.secret=mysuperlongsecretkeywithminimum32chars123
app.jwt.expirationMs=900000
